Xace: provide definitions of new hook functions when xace is disabled
Building with -Dxace=false was generating many failures of the form:
```
../dix/cursor.c: In function ‘AllocARGBCursor’:
../dix/cursor.c:281:10: error: implicit declaration of function
 ‘XaceHookResourceAccess’; did you mean ‘XaceHookPropertyAccess’?
 [-Werror=implicit-function-declaration]
  281 |     rc = XaceHookResourceAccess(client, cid, X11_RESTYPE_CURSOR,
      |          ^~~~~~~~~~~~~~~~~~~~~~
      |          XaceHookPropertyAccess
```
Fixes: https://github.com/X11Libre/xserver/commit/ae3c57333706128134b0b1669a65d267de549bca ("xace: typesafe hook function for XACE_RESOURCE_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/9524ffee89edfb11baf66b5519de01ed3e7f5bd1 ("xace: typesafe hook function for XACE_DEVICE_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/67e468c8bd00c5d835ad427d2a54d120fcc546a8 ("xace: typesafe hook function for XACE_SEND_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/3dfe00d5e086283589dbde5576c76a3b0218d1dc ("xace: typesafe hook function for XACE_RECEIVE_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/922b7685dc45f6ab8b576301ff1f8cf2b494f78c ("xace: typesafe hook function for XACE_CLIENT_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/0f6bb23bc22e7111f64f3adf5f1c3d0c4b672f1e ("xace: typesafe hook function for XACE_EXT_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/47d6c3ad750f7dd645de0c7e11b5575a7b8a1e67 ("xace: typesafe hook function for XACE_SERVER_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/51d8bcfc0db6b0ee56ab9d8b8eff337b713b9278 ("xace: typesafe hook function for XACE_SCREEN_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/305f2d59d8fd0fd697975ece772c7fc30ebe0c06 ("xace: typesafe hook function for XACE_SCREENSAVER_ACCESS")
Fixes: https://github.com/X11Libre/xserver/commit/591d95c79e31fd9d7805b801500e691988fcfaf4 ("xace: typesafe hook function for XACE_AUTH_AVAIL")
Fixes: https://github.com/X11Libre/xserver/commit/facdaae4e8e23f7b8d346ef0f35a814733ab2927 ("xace: typesafe hook function for XACE_KEY_AVAIL")

Signed-off-by: default avatarAlan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/2056>